services:
  api-dev:
    build:
      context: .
      target: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.development
  api-prod:
    build:
      context: .
      target: production
    ports:
      - "8080:3000"
    env_file:
      - .env.production